In [1]:
import numpy as np
import pandas as pd

raw_data_anime = pd.read_csv("anime.csv")
raw_data_rating = pd.read_csv("rating.csv")

In [2]:
display(raw_data_anime.head())
raw_data_rating.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [3]:
raw_data_anime["name"] = raw_data_anime.name.str.replace("&quot;","")
raw_data_anime["name"] = raw_data_anime.name.str.replace("&#039","")

In [4]:
data_user_rating = raw_data_rating[raw_data_rating.rating != -1]
data_user_rating.reset_index(drop=True,inplace=True)
data_user_rating

         user_id  anime_id  rating
0              1      8074      10
1              1     11617      10
2              1     11757      10
3              1     15451      10
4              2     11771      10
...          ...       ...     ...
6337236    73515     16512       7
6337237    73515     17187       9
6337238    73515     22145      10
6337239    73516       790       9
6337240    73516      8074       9

[6337241 rows x 3 columns]

In [5]:
rated_anime_id_list = data_user_rating["anime_id"].unique()

raw_data_anime = raw_data_anime[raw_data_anime["anime_id"].isin(rated_anime_id_list)]
raw_data_anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12288,5541,The Satisfaction,Hentai,OVA,1,4.37,166
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175

In [6]:
type_list = raw_data_anime["type"].unique()[:-1]
tag_list = type_list
tag_list

array(['Movie', 'TV', 'OVA', 'Special', 'Music', 'ONA'], dtype=object)

In [7]:
raw_data_anime[tag_list] = "-"

for t in type_list:
    raw_data_anime[t] = np.where(raw_data_anime["type"] == t, "o","-")
    
raw_data_anime = raw_data_anime.drop(columns=["type", "episodes", "members"])
raw_data_anime

,anime_id,name,genre,rating,Movie,TV,OVA,Special,Music,ONA
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37,o,-,-,-,-,-
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",9.26,-,o,-,-,-,-
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",9.25,-,o,-,-,-,-
3,9253,Steins;Gate,"Sci-Fi, Thriller",9.17,-,o,-,-,-,-
4,9969,Gintama;,"Action, Comedy, Historical, Parody, Samurai, S...",9.16,-,o,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...
12288,5541,The Satisfaction,Hentai,4.37,-,-,o,-,-,-
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,4.15,-,-,o,-,-,-
12290,5543,Under World,Hentai,4.28,-,-,o,-,-,-
12291,5621,Violence Gekiga David no Hoshi,Hentai,4.88,-,-,o,-,-,-
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,4.98,-,-,o,-,-,-

In [8]:
genre_tag_dict = {}
genre_list = []

for s in raw_data_anime.genre.str.split(', '):
    if type(s) == type(0.1):
        continue
        
        
    for g in s:
        genre_tag_dict[g] = 0
        
for key, val in genre_tag_dict.items():
    genre_list.append(key)
    
tag_list = tag_list.tolist()
tag_list += genre_list
genre_list

['Drama',
 'Romance',
 'School',
 'Supernatural',
 'Action',
 'Adventure',
 'Fantasy',
 'Magic',
 'Military',
 'Shounen',
 'Comedy',
 'Historical',
 'Parody',
 'Samurai',
 'Sci-Fi',
 'Thriller',
 'Sports',
 'Super Power',
 'Space',
 'Slice of Life',
 'Mecha',
 'Music',
 'Mystery',
 'Seinen',
 'Martial Arts',
 'Vampire',
 'Shoujo',
 'Horror',
 'Police',
 'Psychological',
 'Demons',
 'Ecchi',
 'Josei',
 'Shounen Ai',
 'Game',
 'Dementia',
 'Harem',
 'Cars',
 'Kids',
 'Shoujo Ai',
 'Hentai',
 'Yaoi',
 'Yuri']

In [9]:
for g in genre_list:
    raw_data_anime[g] = np.where(raw_data_anime.genre.str.find(g) != -1, "o", "-")
    
data_ani = raw_data_anime.drop(columns=["genre"])
data_ani = data_ani.set_index("anime_id")
data_ani

,name,rating,Movie,TV,OVA,Special,Music,ONA,Drama,Romance,...,Shounen Ai,Game,Dementia,Harem,Cars,Kids,Shoujo Ai,Hentai,Yaoi,Yuri
anime_id,,,,,,,,,,,,,,,,,,,,,
32281,Kimi no Na wa.,9.37,o,-,-,-,-,-,o,o,...,-,-,-,-,-,-,-,-,-,-
5114,Fullmetal Alchemist: Brotherhood,9.26,-,o,-,-,-,-,o,-,...,-,-,-,-,-,-,-,-,-,-
28977,Gintama°,9.25,-,o,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9253,Steins;Gate,9.17,-,o,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9969,Gintama;,9.16,-,o,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5541,The Satisfaction,4.37,-,-,o,-,-,-,-,-,...,-,-,-,-,-,-,-,o,-,-
9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,-,-,o,-,-,-,-,-,...,-,-,-,-,-,-,-,o,-,-
5543,Under World,4.28,-,-,o,-,-,-,-,-,...,-,-,-,-,-,-,-,o,-,-
5621,Violence Gekiga David no Hoshi,4.88,-,-,o,-,-,-,-,-,...,-,-,-,-,-,-,-,o,-,-
6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,-,-,o,-,-,-,-,-,...,-,-,-,-,-,-,-,o,-,-

In [10]:
data_merge = pd.merge(data_user_rating, data_ani["name"], on="anime_id")
data_merge

         user_id  anime_id  rating                                name
0              1      8074      10              Highschool of the Dead
1              3      8074       6              Highschool of the Dead
2              5      8074       2              Highschool of the Dead
3             12      8074       6              Highschool of the Dead
4             14      8074       6              Highschool of the Dead
...          ...       ...     ...                                 ...
6337234    69964     23585       7  Haha wo Tazunete Sanzenri Specials
6337235    69964     33659       6      Fushigi na Somera-chan Special
6337236    72800     30738       4        Gamba: Gamba to Nakama-tachi
6337237    73135      8723       5                    Anime Rakugo Kan
6337238    73188      8749       6                            Forestry

[6337239 rows x 4 columns]

In [11]:
rating_matrix = data_merge.pivot_table(values="rating", index="user_id", columns="name")
rating_matrix

name,.hack//G.U. Returner,.hack//G.U. Trilogy,.hack//G.U. Trilogy: Parody Mode,.hack//Gift,.hack//Intermezzo,.hack//Liminality,.hack//Quantum,.hack//Quantum: Sore ike! Bokura no Chimuchimu-chan!!,.hack//Roots,.hack//Sign,...,lilac (bombs Jun Togawa),makemagic,s.CRY.ed,vivi,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki,◯
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for col, item in rating_matrix.items():
    rating_matrix[col] = item.fillna(0)
    
rating_matrix

In [ ]:
rating_matrix_numpy = rating_matrix.values.T
rating_matrix_numpy.shape

In [ ]:
user_count, ani_count = rating_matrix_numpy.shape

from sklearn.decomposition import TruncatedSVD
SVD = TruncatedSVD(n_components=12)
matrix = SVD.fit_transform(rating_matrix_numpy)
matrix.shape

In [ ]:
corr = np.corrcoef(matrix)
corr.shape